version: '3.8'

services:
  postgres:
    image: postgres:14.1
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=clients
      - POSTGRES_USER=clients
      - POSTGRES_DB=clients
    volumes:
      - "db-data:/var/lib/postgresql/data"
  app:
    image: clientsapi
    build:
      context: target
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/clients
      - SPRING_DATASOURCE_USERNAME=clients
      - SPRING_DATASOURCE_PASSWORD=clients
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8090:8080
    depends_on:
      - postgres

volumes:
  db-data: